version: '3'
services:
  web:
    image: nginx:1.25
    volumes:
    - ./:/app
    - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
    links:
      - php

  php:
    image: shieldwalll/php:8.2.12-fpm-mysql-dev 
    volumes:
      - ./:/app
      - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - db
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - .docker/mysql/config.cnf:/.docker/mysql/config.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #CHANGE ME
      MYSQL_DATABASE: easy-php-setup

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    links:
        - db

volumes:
  db-data:
