services:
  web:
    image: nginx:1.25
    volumes:
    - ./:/app
    - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
    links:
      - php

  php:
    image: shieldwalll/php:8.4.13-fpm-mysql-dev 
    volumes:
      - ./:/app
    links:
      - database
      
  database:
    image: mysql:8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - db-data:/var/lib/mysql
      - .docker/mysql/config.cnf:/.docker/mysql/config.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #CHANGE ME
      MYSQL_DATABASE: app
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    links:
        - database

volumes:
  db-data:
